server:
  port:  8084

spring:
  application:
    name: spring-ai-1

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

  datasource:
    url: jdbc:postgresql://localhost:5432/memory_db
    username: raguser
    password: ragpassword
    driver-class-name: org.postgresql.Driver
